// <auto-generated />
using System;
using ContemporaryFinal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContemporaryFinal.Migrations
{
    [DbContext(typeof(CF_DBContext))]
    partial class CF_DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContemporaryFinal.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GroupMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2005, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ian Wolfram",
                            Program = "Information Technology",
                            SchoolYear = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2004, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Madeline Pederson",
                            Program = "Information Technology",
                            SchoolYear = "Junior"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2005, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Joshua Hampton",
                            Program = "Information Technology",
                            SchoolYear = "Junior"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2004, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Han Nguyen",
                            Program = "Information Technology",
                            SchoolYear = "Senior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
